# Generated by Django 3.2.21 on 2023-10-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231001_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='directions',
            field=models.TextField(blank=True),
        ),
    ]
