# Generated by Django 3.2.21 on 2023-10-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_content_post_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='directions',
            field=models.TextField(),
        ),
    ]
