# Generated by Django 3.2.21 on 2023-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
